version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install --save request
      - export BUCKET=blynk-zoom
      - aws cloudformation package --template-file template.yml --s3-bucket blynk-zoom --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
